name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Delete Docker Image and Containers
        run: sudo docker rm -f silversani
      - name: Pull Docker Image from Docker hub
        run: sudo docker pull silversani/incheon:latest
      - name: Execute Docker Container
        run: docker run -d -p 80:3000 -- name silversani silversani/incheon:latest